# Generated by Django 4.2.1 on 2023-05-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='kid',
            field=models.ForeignKey(default=8523, on_delete=django.db.models.deletion.CASCADE, to='points.kid'),
            preserve_default=False,
        ),
    ]
