# Generated by Django 4.2.1 on 2023-05-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_cart_user_cart_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
