# Generated by Django 4.2.1 on 2023-05-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='points_spent',
        ),
    ]
