# Generated by Django 4.2.1 on 2023-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_rename_purchase_date_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='group',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
